spring.application.name=api-server

# DataSource Config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/beauty_platform}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:2559}
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize database schema automatically
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# MyBatis Config
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
